<template>
  <div>
    <h1>color</h1> 
    <h1 v-if="awesome">Vue is awesome!</h1>
 <h1 v-else>Oh no 😢</h1>  
    <input type="color" v-model="color" placeholder="select" /> 
    <input type="button" v-model="button" placeholder="search" />  
    <button @click="showMessage">Submit</button>
    <div v-if="isSubmit">
      {{ this.data }}
    </div>
    <div v-for="(author,index) in books" :key="index"><label><b>author:</b></label>{{author.author}}<br><label><b>country:</b></label>{{author.country}}<br><label><b>imageLink:</b></label>{{author.imageLink}}
              <br><label><b>language:</b></label>{{author.language}}<br><label><b>link:</b></label>{{author.link}}<br><label><b>pages:</b></label>{{author.pages}}<br><label><b>title:</b></label>{{author.title}}<br><label><b>year:</b></label>{{author.year}}</div>
    <div v-for="(title,index) in movies" :key="index"><label><b>Title:</b></label>{{title.Title}}<br><label><b>US Gross:</b></label>{{title["US Gross"]}}<br><label><b>Worldwide Gross:</b></label>{{title["Worldwide Gross"]}}<br><label><b>US DVD Sales:</b></label>{{title["US DVD Sales"]}}<br><label><b>Production Budget:</b></label>{{title["Production Budget"]}}<br><label><b>Release Date:</b></label>{{title["Release Date"]}}<br><label><b>MPAA Rating:</b></label>{{title["MPAA Rating"]}}<br><label><b>Running Time min:</b></label>{{title["Running Time min"]}}<br><label><b>Distributor:</b></label>{{title.Distributor}}<br><label><b>Source:</b></label>{{title.Source}}<br><label><b>Major Genre:</b></label>{{title["Major Genre"]}}<br><label><b>Creative Type:</b></label>{{title["Creative Type"]}}<br><label><b>Director:</b></label>{{title.Director}}<br><label><b>Rotten Tomatoes Rating:</b></label>{{title["Rotten Tomatoes Rating"]}}<br><label><b>IDMB Rating:</b></label>{{title["IDMB Rating"]}}<br><label><b>IDMB Votes:</b></label>{{title["IDMB Votes"]}}</div>
  </div>
</template>
<script>
export default {
  data() {
    return {
      movies: [
        {"Title": "The Land Girls", "US Gross": 146083, "Worldwide Gross": 146083, "US DVD Sales": null, "Production Budget": 8000000, "Release Date": "Jun 12 1998", "MPAA Rating": "R", "Running Time min": null, "Distributor": "Gramercy", "Source": null, "Major Genre": null, "Creative Type": null, "Director": null, "Rotten Tomatoes Rating": null, "IMDB Rating": 6.1, "IMDB Votes": 1071},
    {"Title": "First Love, Last Rites", "US Gross": 10876, "Worldwide Gross": 10876, "US DVD Sales": null, "Production Budget": 300000, "Release Date": "Aug 07 1998", "MPAA Rating": "R", "Running Time min": null, "Distributor": "Strand", "Source": null, "Major Genre": "Drama", "Creative Type": null, "Director": null, "Rotten Tomatoes Rating": null, "IMDB Rating": 6.9, "IMDB Votes": 207},
    {"Title": "I Married a Strange Person", "US Gross": 203134, "Worldwide Gross": 203134, "US DVD Sales": null, "Production Budget": 250000, "Release Date": "Aug 28 1998", "MPAA Rating": null, "Running Time min": null, "Distributor": "Lionsgate", "Source": null, "Major Genre": "Comedy", "Creative Type": null, "Director": null, "Rotten Tomatoes Rating": null, "IMDB Rating": 6.8, "IMDB Votes": 865},
    {"Title": "Let's Talk About Sex", "US Gross": 373615, "Worldwide Gross": 373615, "US DVD Sales": null, "Production Budget": 300000, "Release Date": "Sep 11 1998", "MPAA Rating": null, "Running Time min": null, "Distributor": "Fine Line", "Source": null, "Major Genre": "Comedy", "Creative Type": null, "Director": null, "Rotten Tomatoes Rating": 13, "IMDB Rating": null, "IMDB Votes": null},
    {"Title": "Slam", "US Gross": 1009819, "Worldwide Gross": 1087521, "US DVD Sales": null, "Production Budget": 1000000, "Release Date": "Oct 09 1998", "MPAA Rating": "R", "Running Time min": null, "Distributor": "Trimark", "Source": "Original Screenplay", "Major Genre": "Drama", "Creative Type": "Contemporary Fiction", "Director": null, "Rotten Tomatoes Rating": 62, "IMDB Rating": 3.4, "IMDB Votes": 165},
    {"Title": "Mississippi Mermaid", "US Gross": 24551, "Worldwide Gross": 2624551, "US DVD Sales": null, "Production Budget": 1600000, "Release Date": "Jan 15 1999", "MPAA Rating": null, "Running Time min": null, "Distributor": "MGM", "Source": null, "Major Genre": null, "Creative Type": null, "Director": null, "Rotten Tomatoes Rating": null, "IMDB Rating": null, "IMDB Votes": null},
    {"Title": "Following", "US Gross": 44705, "Worldwide Gross": 44705, "US DVD Sales": null, "Production Budget": 6000, "Release Date": "Apr 04 1999", "MPAA Rating": "R", "Running Time min": null, "Distributor": "Zeitgeist", "Source": null, "Major Genre": null, "Creative Type": null, "Director": "Christopher Nolan", "Rotten Tomatoes Rating": null, "IMDB Rating": 7.7, "IMDB Votes": 15133},
    {"Title": "Foolish", "US Gross": 6026908, "Worldwide Gross": 6026908, "US DVD Sales": null, "Production Budget": 1600000, "Release Date": "Apr 09 1999", "MPAA Rating": "R", "Running Time min": null, "Distributor": "Artisan", "Source": "Original Screenplay", "Major Genre": "Comedy", "Creative Type": "Contemporary Fiction", "Director": null, "Rotten Tomatoes Rating": null, "IMDB Rating": 3.8, "IMDB Votes": 353},
    {"Title": "Pirates", "US Gross": 1641825, "Worldwide Gross": 6341825, "US DVD Sales": null, "Production Budget": 40000000, "Release Date": "Jul 01 1986", "MPAA Rating": "R", "Running Time min": null, "Distributor": null, "Source": null, "Major Genre": null, "Creative Type": null, "Director": "Roman Polanski", "Rotten Tomatoes Rating": 25, "IMDB Rating": 5.8, "IMDB Votes": 3275},
    {"Title": "Duel in the Sun", "US Gross": 20400000, "Worldwide Gross": 20400000, "US DVD Sales": null, "Production Budget": 6000000, "Release Date": "Dec 31 2046", "MPAA Rating": null, "Running Time min": null, "Distributor": null, "Source": null, "Major Genre": null, "Creative Type": null, "Director": null, "Rotten Tomatoes Rating": 86, "IMDB Rating": 7, "IMDB Votes": 2906},
    {"Title": "Tom Jones", "US Gross": 37600000, "Worldwide Gross": 37600000, "US DVD Sales": null, "Production Budget": 1000000, "Release Date": "Oct 07 1963", "MPAA Rating": null, "Running Time min": null, "Distributor": null, "Source": null, "Major Genre": null, "Creative Type": null, "Director": null, "Rotten Tomatoes Rating": 81, "IMDB Rating": 7, "IMDB Votes": 4035},
    {"Title": "Oliver!", "US Gross": 37402877, "Worldwide Gross": 37402877, "US DVD Sales": null, "Production Budget": 10000000, "Release Date": "Dec 11 1968", "MPAA Rating": null, "Running Time min": null, "Distributor": "Sony Pictures", "Source": null, "Major Genre": "Musical", "Creative Type": null, "Director": null, "Rotten Tomatoes Rating": 84, "IMDB Rating": 7.5, "IMDB Votes": 9111},
    {"Title": "To Kill A Mockingbird", "US Gross": 13129846, "Worldwide Gross": 13129846, "US DVD Sales": null, "Production Budget": 2000000, "Release Date": "Dec 25 1962", "MPAA Rating": null, "Running Time min": null, "Distributor": "Universal", "Source": null, "Major Genre": null, "Creative Type": null, "Director": null, "Rotten Tomatoes Rating": 97, "IMDB Rating": 8.4, "IMDB Votes": 82786},
    {"Title": "Tora, Tora, Tora", "US Gross": 29548291, "Worldwide Gross": 29548291, "US DVD Sales": null, "Production Budget": 25000000, "Release Date": "Sep 23 1970", "MPAA Rating": null, "Running Time min": null, "Distributor": null, "Source": null, "Major Genre": null, "Creative Type": null, "Director": "Richard Fleischer", "Rotten Tomatoes Rating": null, "IMDB Rating": null, "IMDB Votes": null},
    {"Title": "Hollywood Shuffle", "US Gross": 5228617, "Worldwide Gross": 5228617, "US DVD Sales": null, "Production Budget": 100000, "Release Date": "Mar 01 1987", "MPAA Rating": null, "Running Time min": null, "Distributor": null, "Source": null, "Major Genre": null, "Creative Type": null, "Director": null, "Rotten Tomatoes Rating": 87, "IMDB Rating": 6.8, "IMDB Votes": 1532},
    {"Title": "Over the Hill to the Poorhouse", "US Gross": 3000000, "Worldwide Gross": 3000000, "US DVD Sales": null, "Production Budget": 100000, "Release Date": "Sep 17 2020", "MPAA Rating": null, "Running Time min": null, "Distributor": null, "Source": null, "Major Genre": null, "Creative Type": null, "Director": null, "Rotten Tomatoes Rating": null, "IMDB Rating": null, "IMDB Votes": null},
    {"Title": "Wilson", "US Gross": 2000000, "Worldwide Gross": 2000000, "US DVD Sales": null, "Production Budget": 5200000, "Release Date": "Aug 01 2044", "MPAA Rating": null, "Running Time min": null, "Distributor": null, "Source": null, "Major Genre": null, "Creative Type": null, "Director": null, "Rotten Tomatoes Rating": null, "IMDB Rating": 7, "IMDB Votes": 451},
    {"Title": "Darling Lili", "US Gross": 5000000, "Worldwide Gross": 5000000, "US DVD Sales": null, "Production Budget": 22000000, "Release Date": "Jan 01 1970", "MPAA Rating": null, "Running Time min": null, "Distributor": null, "Source": null, "Major Genre": null, "Creative Type": null, "Director": "Blake Edwards", "Rotten Tomatoes Rating": null, "IMDB Rating": 6.1, "IMDB Votes": 858},
    {"Title": "The Ten Commandments", "US Gross": 80000000, "Worldwide Gross": 80000000, "US DVD Sales": null, "Production Budget": 13500000, "Release Date": "Oct 05 1956", "MPAA Rating": null, "Running Time min": null, "Distributor": null, "Source": null, "Major Genre": null, "Creative Type": null, "Director": null, "Rotten Tomatoes Rating": 90, "IMDB Rating": 2.5, "IMDB Votes": 1677},
    {"Title": "12 Angry Men", "US Gross": 0, "Worldwide Gross": 0, "US DVD Sales": null, "Production Budget": 340000, "Release Date": "Apr 13 1957", "MPAA Rating": null, "Running Time min": null, "Distributor": "United Artists", "Source": "Original Screenplay", "Major Genre": "Drama", "Creative Type": null, "Director": "Sidney Lumet", "Rotten Tomatoes Rating": null, "IMDB Rating": 8.9, "IMDB Votes": 119101},
    {"Title": "Twelve Monkeys", "US Gross": 57141459, "Worldwide Gross": 168841459, "US DVD Sales": null, "Production Budget": 29000000, "Release Date": "Dec 27 1995", "MPAA Rating": "R", "Running Time min": null, "Distributor": "Universal", "Source": "Based on Short Film", "Major Genre": "Drama", "Creative Type": "Science Fiction", "Director": "Terry Gilliam", "Rotten Tomatoes Rating": null, "IMDB Rating": 8.1, "IMDB Votes": 169858},
    {"Title": 1776, "US Gross": 0, "Worldwide Gross": 0, "US DVD Sales": null, "Production Budget": 4000000, "Release Date": "Nov 09 1972", "MPAA Rating": "PG", "Running Time min": null, "Distributor": "Sony/Columbia", "Source": "Based on Play", "Major Genre": "Drama", "Creative Type": "Historical Fiction", "Director": null, "Rotten Tomatoes Rating": 57, "IMDB Rating": 7, "IMDB Votes": 4099},
    {"Title": 1941, "US Gross": 34175000, "Worldwide Gross": 94875000, "US DVD Sales": null, "Production Budget": 32000000, "Release Date": "Dec 14 1979", "MPAA Rating": null, "Running Time min": null, "Distributor": "Universal", "Source": "Original Screenplay", "Major Genre": "Comedy", "Creative Type": "Historical Fiction", "Director": "Steven Spielberg", "Rotten Tomatoes Rating": 33, "IMDB Rating": 5.6, "IMDB Votes": 13364},
    {"Title": "Chacun sa nuit", "US Gross": 18435, "Worldwide Gross": 18435, "US DVD Sales": null, "Production Budget": 1900000, "Release Date": "Jun 29 2007", "MPAA Rating": "Not Rated", "Running Time min": null, "Distributor": "Strand", "Source": "Original Screenplay", "Major Genre": "Thriller/Suspense", "Creative Type": null, "Director": null, "Rotten Tomatoes Rating": null, "IMDB Rating": 6.3, "IMDB Votes": 365},
    {"Title": "2001: A Space Odyssey", "US Gross": 56700000, "Worldwide Gross": 68700000, "US DVD Sales": null, "Production Budget": 10500000, "Release Date": "Apr 02 1968", "MPAA Rating": null, "Running Time min": null, "Distributor": null, "Source": "Original Screenplay", "Major Genre": null, "Creative Type": "Science Fiction", "Director": "Stanley Kubrick", "Rotten Tomatoes Rating": 96, "IMDB Rating": 8.4, "IMDB Votes": 160342},
    {"Title": "20,000 Leagues Under the Sea", "US Gross": 28200000, "Worldwide Gross": 28200000, "US DVD Sales": null, "Production Budget": 5000000, "Release Date": "Dec 23 1954", "MPAA Rating": null, "Running Time min": null, "Distributor": "Walt Disney Pictures", "Source": "Based on Book/Short Story", "Major Genre": "Adventure", "Creative Type": null, "Director": "Richard Fleischer", "Rotten Tomatoes Rating": 92, "IMDB Rating": null, "IMDB Votes": null},
    {"Title": "20,000 Leagues Under the Sea", "US Gross": 8000000, "Worldwide Gross": 8000000, "US DVD Sales": null, "Production Budget": 200000, "Release Date": "Dec 24 2016", "MPAA Rating": null, "Running Time min": null, "Distributor": null, "Source": "Based on Book/Short Story", "Major Genre": "Adventure", "Creative Type": null, "Director": null, "Rotten Tomatoes Rating": null, "IMDB Rating": null, "IMDB Votes": null},
    {"Title": "24 7: Twenty Four Seven", "US Gross": 72544, "Worldwide Gross": 72544, "US DVD Sales": null, "Production Budget": 2000000, "Release Date": "Apr 15 1998", "MPAA Rating": "R", "Running Time min": null, "Distributor": "October Films", "Source": "Original Screenplay", "Major Genre": "Comedy", "Creative Type": null, "Director": "Shane Meadows", "Rotten Tomatoes Rating": null, "IMDB Rating": 6.9, "IMDB Votes": 1417},
    {"Title": "Twin Falls Idaho", "US Gross": 985341, "Worldwide Gross": 1027228, "US DVD Sales": null, "Production Budget": 500000, "Release Date": "Jul 30 1999", "MPAA Rating": "R", "Running Time min": null, "Distributor": "Sony Pictures Classics", "Source": "Original Screenplay", "Major Genre": "Drama", "Creative Type": "Contemporary Fiction", "Director": "Michael Polish", "Rotten Tomatoes Rating": 77, "IMDB Rating": 7.1, "IMDB Votes": 2810},
    {"Title": "Three Kingdoms: Resurrection of the Dragon", "US Gross": 0, "Worldwide Gross": 22139590, "US DVD Sales": null, "Production Budget": 20000000, "Release Date": "Apr 03 2008", "MPAA Rating": "R", "Running Time min": null, "Distributor": null, "Source": "Based on Book/Short Story", "Major Genre": "Action", "Creative Type": "Historical Fiction", "Director": null, "Rotten Tomatoes Rating": null, "IMDB Rating": null, "IMDB Votes": null},
    {"Title": "3 Men and a Baby", "US Gross": 167780960, "Worldwide Gross": 167780960, "US DVD Sales": null, "Production Budget": 15000000, "Release Date": "Nov 25 1987", "MPAA Rating": null, "Running Time min": null, "Distributor": "Walt Disney Pictures", "Source": "Remake", "Major Genre": "Comedy", "Creative Type": "Contemporary Fiction", "Director": "Leonard Nimoy", "Rotten Tomatoes Rating": null, "IMDB Rating": 5.7, "IMDB Votes": 16764},
    {"Title": "3 Ninjas Kick Back", "US Gross": 11744960, "Worldwide Gross": 11744960, "US DVD Sales": null, "Production Budget": 20000000, "Release Date": "May 06 1994", "MPAA Rating": "PG", "Running Time min": null, "Distributor": "Walt Disney Pictures", "Source": "Original Screenplay", "Major Genre": "Action", "Creative Type": "Contemporary Fiction", "Director": null, "Rotten Tomatoes Rating": 17, "IMDB Rating": 3.2, "IMDB Votes": 3107},
    {"Title": "Forty Shades of Blue", "US Gross": 75828, "Worldwide Gross": 172569, "US DVD Sales": null, "Production Budget": 1500000, "Release Date": "Sep 28 2005", "MPAA Rating": "R", "Running Time min": null, "Distributor": "Vitagraph Films", "Source": "Original Screenplay", "Major Genre": "Drama", "Creative Type": null, "Director": null, "Rotten Tomatoes Rating": null, "IMDB Rating": 6, "IMDB Votes": 873},
    {"Title": "42nd Street", "US Gross": 2300000, "Worldwide Gross": 2300000, "US DVD Sales": null, "Production Budget": 439000, "Release Date": "Mar 09 2033", "MPAA Rating": null, "Running Time min": null, "Distributor": "Warner Bros.", "Source": "Based on Book/Short Story", "Major Genre": "Musical", "Creative Type": null, "Director": null, "Rotten Tomatoes Rating": 95, "IMDB Rating": 7.7, "IMDB Votes": 4263},
    {"Title": "Four Rooms", "US Gross": 4301000, "Worldwide Gross": 4301000, "US DVD Sales": null, "Production Budget": 4000000, "Release Date": "Dec 25 1995", "MPAA Rating": "R", "Running Time min": null, "Distributor": "Miramax", "Source": "Original Screenplay", "Major Genre": "Comedy", "Creative Type": "Contemporary Fiction", "Director": "Robert Rodriguez", "Rotten Tomatoes Rating": 14, "IMDB Rating": 6.4, "IMDB Votes": 34328},
    {"Title": "The Four Seasons", "US Gross": 42488161, "Worldwide Gross": 42488161, "US DVD Sales": null, "Production Budget": 6500000, "Release Date": "May 22 1981", "MPAA Rating": null, "Running Time min": null, "Distributor": "Universal", "Source": "Original Screenplay", "Major Genre": "Comedy", "Creative Type": "Contemporary Fiction", "Director": "Alan Alda", "Rotten Tomatoes Rating": 71, "IMDB Rating": 7, "IMDB Votes": 1814},
    {"Title": "Four Weddings and a Funeral", "US Gross": 52700832, "Worldwide Gross": 242895809, "US DVD Sales": null, "Production Budget": 4500000, "Release Date": "Mar 09 1994", "MPAA Rating": "R", "Running Time min": null, "Distributor": "Gramercy", "Source": "Original Screenplay", "Major Genre": "Romantic Comedy", "Creative Type": "Contemporary Fiction", "Director": "Mike Newell", "Rotten Tomatoes Rating": 96, "IMDB Rating": 7.1, "IMDB Votes": 39003},
    {"Title": "51 Birch Street", "US Gross": 84689, "Worldwide Gross": 84689, "US DVD Sales": null, "Production Budget": 350000, "Release Date": "Oct 18 2006", "MPAA Rating": "Not Rated", "Running Time min": null, "Distributor": "Truly Indie", "Source": null, "Major Genre": null, "Creative Type": null, "Director": null, "Rotten Tomatoes Rating": 97, "IMDB Rating": 7.4, "IMDB Votes": 439},
    {"Title": "55 Days at Peking", "US Gross": 10000000, "Worldwide Gross": 10000000, "US DVD Sales": null, "Production Budget": 17000000, "Release Date": "Dec 31 1962", "MPAA Rating": null, "Running Time min": null, "Distributor": null, "Source": "Original Screenplay", "Major Genre": "Drama", "Creative Type": null, "Director": null, "Rotten Tomatoes Rating": 57, "IMDB Rating": 6.8, "IMDB Votes": 2104},
    {"Title": "Nine 1/2 Weeks", "US Gross": 6734844, "Worldwide Gross": 6734844, "US DVD Sales": null, "Production Budget": 18000000, "Release Date": "Feb 21 1986", "MPAA Rating": null, "Running Time min": null, "Distributor": "MGM", "Source": "Based on Book/Short Story", "Major Genre": "Drama", "Creative Type": "Contemporary Fiction", "Director": "Adrian Lyne", "Rotten Tomatoes Rating": null, "IMDB Rating": 5.4, "IMDB Votes": 12731},
    {"Title": "AstÈrix aux Jeux Olympiques", "US Gross": 999811, "Worldwide Gross": 132999811, "US DVD Sales": null, "Production Budget": 113500000, "Release Date": "Jul 04 2008", "MPAA Rating": "Not Rated", "Running Time min": null, "Distributor": "Alliance", "Source": "Based on Comic/Graphic Novel", "Major Genre": "Adventure", "Creative Type": "Fantasy", "Director": null, "Rotten Tomatoes Rating": null, "IMDB Rating": 4.9, "IMDB Votes": 5620},
    {"Title": "The Abyss", "US Gross": 54243125, "Worldwide Gross": 54243125, "US DVD Sales": null, "Production Budget": 70000000, "Release Date": "Aug 09 1989", "MPAA Rating": "PG-13", "Running Time min": null, "Distributor": "20th Century Fox", "Source": "Original Screenplay", "Major Genre": "Action", "Creative Type": "Science Fiction", "Director": "James Cameron", "Rotten Tomatoes Rating": 88, "IMDB Rating": 7.6, "IMDB Votes": 51018},
    {"Title": "Action Jackson", "US Gross": 20257000, "Worldwide Gross": 20257000, "US DVD Sales": null, "Production Budget": 7000000, "Release Date": "Feb 12 1988", "MPAA Rating": null, "Running Time min": null, "Distributor": "Lorimar Motion Pictures", "Source": "Original Screenplay", "Major Genre": "Action", "Creative Type": "Contemporary Fiction", "Director": null, "Rotten Tomatoes Rating": 10, "IMDB Rating": 4.6, "IMDB Votes": 3856},
    {"Title": "Ace Ventura: Pet Detective", "US Gross": 72217396, "Worldwide Gross": 107217396, "US DVD Sales": null, "Production Budget": 12000000, "Release Date": "Feb 04 1994", "MPAA Rating": "PG-13", "Running Time min": null, "Distributor": "Warner Bros.", "Source": "Original Screenplay", "Major Genre": "Comedy", "Creative Type": "Contemporary Fiction", "Director": "Tom Shadyac", "Rotten Tomatoes Rating": 49, "IMDB Rating": 6.6, "IMDB Votes": 63543},
    {"Title": "Ace Ventura: When Nature Calls", "US Gross": 108360063, "Worldwide Gross": 212400000, "US DVD Sales": null, "Production Budget": 30000000, "Release Date": "Nov 10 1995", "MPAA Rating": "PG-13", "Running Time min": null, "Distributor": "Warner Bros.", "Source": "Original Screenplay", "Major Genre": "Comedy", "Creative Type": "Contemporary Fiction", "Director": "Steve Oedekerk", "Rotten Tomatoes Rating": null, "IMDB Rating": 5.6, "IMDB Votes": 51275},
    {"Title": "April Fool's Day", "US Gross": 12947763, "Worldwide Gross": 12947763, "US DVD Sales": null, "Production Budget": 5000000, "Release Date": "Mar 27 1986", "MPAA Rating": null, "Running Time min": null, "Distributor": "Paramount Pictures", "Source": "Original Screenplay", "Major Genre": "Horror", "Creative Type": "Contemporary Fiction", "Director": null, "Rotten Tomatoes Rating": 31, "IMDB Rating": null, "IMDB Votes": null},
    {"Title": "Among Giants", "US Gross": 64359, "Worldwide Gross": 64359, "US DVD Sales": null, "Production Budget": 4000000, "Release Date": "Mar 26 1999", "MPAA Rating": "R", "Running Time min": null, "Distributor": "Fox Searchlight", "Source": "Original Screenplay", "Major Genre": "Romantic Comedy", "Creative Type": null, "Director": null, "Rotten Tomatoes Rating": null, "IMDB Rating": 5.7, "IMDB Votes": 546},
    {"Title": "Annie Get Your Gun", "US Gross": 8000000, "Worldwide Gross": 8000000, "US DVD Sales": null, "Production Budget": 3768785, "Release Date": "May 17 1950", "MPAA Rating": null, "Running Time min": null, "Distributor": "MGM", "Source": "Based on Book/Short Story", "Major Genre": "Musical", "Creative Type": null, "Director": null, "Rotten Tomatoes Rating": 100, "IMDB Rating": 7.1, "IMDB Votes": 1326},
    {"Title": "Alice in Wonderland", "US Gross": 0, "Worldwide Gross": 0, "US DVD Sales": null, "Production Budget": 3000000, "Release Date": "Jul 28 1951", "MPAA Rating": null, "Running Time min": null, "Distributor": "RKO Radio Pictures", "Source": "Based on Book/Short Story", "Major Genre": "Musical", "Creative Type": null, "Director": null, "Rotten Tomatoes Rating": 20, "IMDB Rating": 6.7, "IMDB Votes": 63458},
    {"Title": "The Princess and the Cobbler", "US Gross": 669276, "Worldwide Gross": 669276, "US DVD Sales": null, "Production Budget": 24000000, "Release Date": "Aug 25 1995", "MPAA Rating": "G", "Running Time min": null, "Distributor": "Miramax", "Source": "Original Screenplay", "Major Genre": "Adventure", "Creative Type": "Fantasy", "Director": null, "Rotten Tomatoes Rating": null, "IMDB Rating": 7.3, "IMDB Votes": 893},
    {"Title": "The Alamo", "US Gross": 7900000, "Worldwide Gross": 7900000, "US DVD Sales": null, "Production Budget": 12000000, "Release Date": "Oct 24 1960", "MPAA Rating": "PG-13", "Running Time min": null, "Distributor": "United Artists", "Source": "Original Screenplay", "Major Genre": "Western", "Creative Type": "Historical Fiction", "Director": "John Wayne", "Rotten Tomatoes Rating": 54, "IMDB Rating": 5.9, "IMDB Votes": 10063},
    {"Title": "Alexander's Ragtime Band", "US Gross": 4000000, "Worldwide Gross": 4000000, "US DVD Sales": null, "Production Budget": 2000000, "Release Date": "Dec 31 1937", "MPAA Rating": null, "Running Time min": null, "Distributor": "20th Century Fox", "Source": "Original Screenplay", "Major Genre": "Drama", "Creative Type": null, "Director": null, "Rotten Tomatoes Rating": null, "IMDB Rating": null, "IMDB Votes": null},
    {"Title": "Alive", "US Gross": 36299670, "Worldwide Gross": 36299670, "US DVD Sales": null, "Production Budget": 32000000, "Release Date": "Jan 15 1993", "MPAA Rating": "R", "Running Time min": null, "Distributor": "Walt Disney Pictures", "Source": "Based on Book/Short Story", "Major Genre": "Adventure", "Creative Type": "Dramatization", "Director": "Frank Marshall", "Rotten Tomatoes Rating": 71, "IMDB Rating": 3.2, "IMDB Votes": 124},
    {"Title": "Amen", "US Gross": 274299, "Worldwide Gross": 274299, "US DVD Sales": null, "Production Budget": 14000000, "Release Date": "Jan 24 2003", "MPAA Rating": "Not Rated", "Running Time min": null, "Distributor": "Kino International", "Source": "Based on Play", "Major Genre": "Drama", "Creative Type": null, "Director": "Costa-Gavras", "Rotten Tomatoes Rating": null, "IMDB Rating": 7.4, "IMDB Votes": 5416},
    {"Title": "American Graffiti", "US Gross": 115000000, "Worldwide Gross": 140000000, "US DVD Sales": null, "Production Budget": 777000, "Release Date": "Aug 11 1973", "MPAA Rating": null, "Running Time min": null, "Distributor": "Universal", "Source": "Original Screenplay", "Major Genre": "Comedy", "Creative Type": null, "Director": "George Lucas", "Rotten Tomatoes Rating": 97, "IMDB Rating": 7.6, "IMDB Votes": 30952},
    {"Title": "American Ninja 2: The Confrontation", "US Gross": 4000000, "Worldwide Gross": 4000000, "US DVD Sales": null, "Production Budget": 350000, "Release Date": "Dec 31 1986", "MPAA Rating": null, "Running Time min": null, "Distributor": null, "Source": "Original Screenplay", "Major Genre": "Action", "Creative Type": null, "Director": "Sam Firstenberg", "Rotten Tomatoes Rating": null, "IMDB Rating": 3.7, "IMDB Votes": 2495},
    {"Title": "The American President", "US Gross": 60022813, "Worldwide Gross": 107822813, "US DVD Sales": null, "Production Budget": 62000000, "Release Date": "Nov 17 1995", "MPAA Rating": "PG-13", "Running Time min": null, "Distributor": "Sony Pictures", "Source": "Original Screenplay", "Major Genre": "Romantic Comedy", "Creative Type": "Contemporary Fiction", "Director": "Rob Reiner", "Rotten Tomatoes Rating": 90, "IMDB Rating": 6.8, "IMDB Votes": 22780},
    {"Title": "Annie Hall", "US Gross": 38251425, "Worldwide Gross": 38251425, "US DVD Sales": null, "Production Budget": 4000000, "Release Date": "Apr 20 1977", "MPAA Rating": null, "Running Time min": null, "Distributor": "MGM", "Source": "Original Screenplay", "Major Genre": "Comedy", "Creative Type": null, "Director": "Woody Allen", "Rotten Tomatoes Rating": 98, "IMDB Rating": 8.2, "IMDB Votes": 65406},
    {"Title": "Anatomie", "US Gross": 9598, "Worldwide Gross": 9598, "US DVD Sales": null, "Production Budget": 2500000, "Release Date": "Sep 08 2000", "MPAA Rating": "Not Rated", "Running Time min": null, "Distributor": "Sony Pictures", "Source": "Original Screenplay", "Major Genre": "Horror", "Creative Type": null, "Director": null, "Rotten Tomatoes Rating": null, "IMDB Rating": 6.1, "IMDB Votes": 6266},
    {"Title": "The Adventures of Huck Finn", "US Gross": 24103594, "Worldwide Gross": 24103594, "US DVD Sales": null, "Production Budget": 6500000, "Release Date": "Apr 02 1993", "MPAA Rating": "PG", "Running Time min": null, "Distributor": "Walt Disney Pictures", "Source": "Based on Book/Short Story", "Major Genre": "Adventure", "Creative Type": "Historical Fiction", "Director": "Stephen Sommers", "Rotten Tomatoes Rating": 62, "IMDB Rating": 5.8, "IMDB Votes": 3095},
    {"Title": "The Apartment", "US Gross": 18600000, "Worldwide Gross": 24600000, "US DVD Sales": null, "Production Budget": 3000000, "Release Date": "Dec 31 1959", "MPAA Rating": null, "Running Time min": null, "Distributor": "United Artists", "Source": "Original Screenplay", "Major Genre": "Romantic Comedy", "Creative Type": null, "Director": "Billy Wilder", "Rotten Tomatoes Rating": 91, "IMDB Rating": 8.4, "IMDB Votes": 36485},
    {"Title": "Apocalypse Now", "US Gross": 78800000, "Worldwide Gross": 78800000, "US DVD Sales": 3479242, "Production Budget": 31500000, "Release Date": "Aug 15 1979", "MPAA Rating": "R", "Running Time min": null, "Distributor": "MGM", "Source": "Based on Book/Short Story", "Major Genre": "Action", "Creative Type": "Historical Fiction", "Director": "Francis Ford Coppola", "Rotten Tomatoes Rating": 98, "IMDB Rating": 8.6, "IMDB Votes": 173141},
    {"Title": "Arachnophobia", "US Gross": 53208180, "Worldwide Gross": 53208180, "US DVD Sales": null, "Production Budget": 31000000, "Release Date": "Jul 18 1990", "MPAA Rating": null, "Running Time min": null, "Distributor": "Walt Disney Pictures", "Source": "Original Screenplay", "Major Genre": "Thriller/Suspense", "Creative Type": "Science Fiction", "Director": "Frank Marshall", "Rotten Tomatoes Rating": 85, "IMDB Rating": 6.2, "IMDB Votes": 20528},
    {"Title": "Arn - Tempelriddaren", "US Gross": 0, "Worldwide Gross": 14900000, "US DVD Sales": null, "Production Budget": 16500000, "Release Date": "Dec 25 2007", "MPAA Rating": "R", "Running Time min": null, "Distributor": null, "Source": "Based on Book/Short Story", "Major Genre": "Action", "Creative Type": "Historical Fiction", "Director": null, "Rotten Tomatoes Rating": null, "IMDB Rating": 6.4, "IMDB Votes": 6251},
    {"Title": "Arnolds Park", "US Gross": 23616, "Worldwide Gross": 23616, "US DVD Sales": null, "Production Budget": 600000, "Release Date": "Oct 19 2007", "MPAA Rating": "PG-13", "Running Time min": null, "Distributor": "The Movie Partners", "Source": "Original Screenplay", "Major Genre": "Thriller/Suspense", "Creative Type": "Contemporary Fiction", "Director": null, "Rotten Tomatoes Rating": null, "IMDB Rating": 5.1, "IMDB Votes": 77},
    {"Title": "Sweet Sweetback's Baad Asssss Song", "US Gross": 15200000, "Worldwide Gross": 15200000, "US DVD Sales": null, "Production Budget": 150000, "Release Date": "Jan 01 1971", "MPAA Rating": null, "Running Time min": null, "Distributor": null, "Source": null, "Major Genre": null, "Creative Type": null, "Director": null, "Rotten Tomatoes Rating": null, "IMDB Rating": 5.6, "IMDB Votes": 1769},
    {"Title": "And Then Came Love", "US Gross": 8158, "Worldwide Gross": 8158, "US DVD Sales": null, "Production Budget": 989000, "Release Date": "Jun 01 2007", "MPAA Rating": "Not Rated", "Running Time min": null, "Distributor": "Fox Meadow", "Source": null, "Major Genre": "Comedy", "Creative Type": null, "Director": null, "Rotten Tomatoes Rating": 17, "IMDB Rating": 4.4, "IMDB Votes": 200},
    {"Title": "Around the World in 80 Days", "US Gross": 42000000, "Worldwide Gross": 42000000, "US DVD Sales": null, "Production Budget": 6000000, "Release Date": "Oct 17 1956", "MPAA Rating": "PG", "Running Time min": null, "Distributor": "United Artists", "Source": "Based on Book/Short Story", "Major Genre": "Adventure", "Creative Type": null, "Director": null, "Rotten Tomatoes Rating": 73, "IMDB Rating": 5.6, "IMDB Votes": 21516},
    {"Title": "Barbarella", "US Gross": 0, "Worldwide Gross": 0, "US DVD Sales": null, "Production Budget": 9000000, "Release Date": "Oct 10 1968", "MPAA Rating": null, "Running Time min": null, "Distributor": "Paramount Pictures", "Source": "Based on Comic/Graphic Novel", "Major Genre": "Adventure", "Creative Type": "Science Fiction", "Director": null, "Rotten Tomatoes Rating": 74, "IMDB Rating": 5.7, "IMDB Votes": 10794},
    {"Title": "Barry Lyndon", "US Gross": 20000000, "Worldwide Gross": 20000000, "US DVD Sales": null, "Production Budget": 11000000, "Release Date": "Dec 31 1974", "MPAA Rating": null, "Running Time min": null, "Distributor": "Warner Bros.", "Source": "Based on Book/Short Story", "Major Genre": "Drama", "Creative Type": null, "Director": "Stanley Kubrick", "Rotten Tomatoes Rating": 94, "IMDB Rating": 8.1, "IMDB Votes": 39909},
    {"Title": "Barbarians, The", "US Gross": 800000, "Worldwide Gross": 800000, "US DVD Sales": null, "Production Budget": 4000000, "Release Date": "Mar 01 1987", "MPAA Rating": null, "Running Time min": null, "Distributor": null, "Source": null, "Major Genre": null, "Creative Type": null, "Director": null, "Rotten Tomatoes Rating": null, "IMDB Rating": 5.4, "IMDB Votes": 236},
    {"Title": "Babe", "US Gross": 63658910, "Worldwide Gross": 246100000, "US DVD Sales": null, "Production Budget": 30000000, "Release Date": "Aug 04 1995", "MPAA Rating": "G", "Running Time min": null, "Distributor": "Universal", "Source": "Based on Book/Short Story", "Major Genre": "Adventure", "Creative Type": "Contemporary Fiction", "Director": "Chris Noonan", "Rotten Tomatoes Rating": 98, "IMDB Rating": 7.3, "IMDB Votes": 35644},
    {"Title": "Boynton Beach Club", "US Gross": 3127472, "Worldwide Gross": 3127472, "US DVD Sales": null, "Production Budget": 2900000, "Release Date": "Mar 24 2006", "MPAA Rating": "R", "Running Time min": 104, "Distributor": "Wingate Distribution", "Source": "Original Screenplay", "Major Genre": "Romantic Comedy", "Creative Type": "Contemporary Fiction", "Director": null, "Rotten Tomatoes Rating": null, "IMDB Rating": null, "IMDB Votes": null},
    {"Title": "Baby's Day Out", "US Gross": 16581575, "Worldwide Gross": 16581575, "US DVD Sales": null, "Production Budget": 50000000, "Release Date": "Jul 01 1994", "MPAA Rating": "PG", "Running Time min": null, "Distributor": "20th Century Fox", "Source": "Original Screenplay", "Major Genre": "Comedy", "Creative Type": "Contemporary Fiction", "Director": "Patrick Read Johnson", "Rotten Tomatoes Rating": 21, "IMDB Rating": 5, "IMDB Votes": 8332},
    {"Title": "Bound by Honor", "US Gross": 4496583, "Worldwide Gross": 4496583, "US DVD Sales": null, "Production Budget": 35000000, "Release Date": "Apr 16 1993", "MPAA Rating": null, "Running Time min": null, "Distributor": "Walt Disney Pictures", "Source": "Original Screenplay", "Major Genre": null, "Creative Type": null, "Director": "Taylor Hackford", "Rotten Tomatoes Rating": null, "IMDB Rating": 7.7, "IMDB Votes": 10142},
    {"Title": "Bon Cop, Bad Cop", "US Gross": 12671300, "Worldwide Gross": 12671300, "US DVD Sales": null, "Production Budget": 8000000, "Release Date": "Aug 04 2006", "MPAA Rating": "Not Rated", "Running Time min": null, "Distributor": "Alliance", "Source": "Original Screenplay", "Major Genre": "Comedy", "Creative Type": "Contemporary Fiction", "Director": null, "Rotten Tomatoes Rating": 67, "IMDB Rating": 6.9, "IMDB Votes": 151},
    {"Title": "Back to the Future", "US Gross": 210609762, "Worldwide Gross": 381109762, "US DVD Sales": null, "Production Budget": 19000000, "Release Date": "Jul 03 1985", "MPAA Rating": null, "Running Time min": null, "Distributor": "Universal", "Source": "Original Screenplay", "Major Genre": "Adventure", "Creative Type": "Science Fiction", "Director": "Robert Zemeckis", "Rotten Tomatoes Rating": 96, "IMDB Rating": 8.4, "IMDB Votes": 201598},
    {"Title": "Back to the Future Part II", "US Gross": 118450002, "Worldwide Gross": 332000000, "US DVD Sales": null, "Production Budget": 40000000, "Release Date": "Nov 22 1989", "MPAA Rating": null, "Running Time min": null, "Distributor": "Universal", "Source": "Original Screenplay", "Major Genre": "Adventure", "Creative Type": "Science Fiction", "Director": "Robert Zemeckis", "Rotten Tomatoes Rating": 64, "IMDB Rating": 7.5, "IMDB Votes": 87341},
    {"Title": "Back to the Future Part III", "US Gross": 87666629, "Worldwide Gross": 243700000, "US DVD Sales": null, "Production Budget": 40000000, "Release Date": "May 24 1990", "MPAA Rating": null, "Running Time min": null, "Distributor": "Universal", "Source": "Original Screenplay", "Major Genre": "Adventure", "Creative Type": "Science Fiction", "Director": "Robert Zemeckis", "Rotten Tomatoes Rating": 71, "IMDB Rating": 7.1, "IMDB Votes": 77541},
    {"Title": "Butch Cassidy and the Sundance Kid", "US Gross": 102308900, "Worldwide Gross": 102308900, "US DVD Sales": null, "Production Budget": 6000000, "Release Date": "Oct 24 1969", "MPAA Rating": null, "Running Time min": null, "Distributor": "20th Century Fox", "Source": null, "Major Genre": "Western", "Creative Type": "Historical Fiction", "Director": "George Roy Hill", "Rotten Tomatoes Rating": 90, "IMDB Rating": 8.2, "IMDB Votes": 57602},
    {"Title": "Bad Boys", "US Gross": 65647413, "Worldwide Gross": 141247413, "US DVD Sales": null, "Production Budget": 23000000, "Release Date": "Apr 07 1995", "MPAA Rating": "R", "Running Time min": null, "Distributor": "Sony Pictures", "Source": "Original Screenplay", "Major Genre": "Action", "Creative Type": "Contemporary Fiction", "Director": "Michael Bay", "Rotten Tomatoes Rating": 39, "IMDB Rating": 6.6, "IMDB Votes": 53929},
    {"Title": "Body Double", "US Gross": 8801940, "Worldwide Gross": 8801940, "US DVD Sales": null, "Production Budget": 10000000, "Release Date": "Oct 26 1984", "MPAA Rating": null, "Running Time min": null, "Distributor": "Sony/Columbia", "Source": "Original Screenplay", "Major Genre": "Thriller/Suspense", "Creative Type": "Contemporary Fiction", "Director": "Brian De Palma", "Rotten Tomatoes Rating": 84, "IMDB Rating": 6.4, "IMDB Votes": 9738},
    {"Title": "The Beast from 20,000 Fathoms", "US Gross": 5000000, "Worldwide Gross": 5000000, "US DVD Sales": null, "Production Budget": 210000, "Release Date": "Jun 13 1953", "MPAA Rating": null, "Running Time min": null, "Distributor": "Warner Bros.", "Source": "Based on Book/Short Story", "Major Genre": null, "Creative Type": null, "Director": null, "Rotten Tomatoes Rating": 90, "IMDB Rating": null, "IMDB Votes": null},
    {"Title": "Beastmaster 2: Through the Portal of Time", "US Gross": 773490, "Worldwide Gross": 773490, "US DVD Sales": null, "Production Budget": 6000000, "Release Date": "Aug 30 1991", "MPAA Rating": null, "Running Time min": null, "Distributor": "New Line", "Source": "Based on Book/Short Story", "Major Genre": null, "Creative Type": "Fantasy", "Director": null, "Rotten Tomatoes Rating": 17, "IMDB Rating": 3.3, "IMDB Votes": 1327},
    {"Title": "The Beastmaster", "US Gross": 10751126, "Worldwide Gross": 10751126, "US DVD Sales": null, "Production Budget": 5000000, "Release Date": "Aug 20 1982", "MPAA Rating": null, "Running Time min": null, "Distributor": "MGM", "Source": "Based on Book/Short Story", "Major Genre": "Action", "Creative Type": "Fantasy", "Director": null, "Rotten Tomatoes Rating": 50, "IMDB Rating": 5.7, "IMDB Votes": 5734},
    {"Title": "Ben-Hur", "US Gross": 9000000, "Worldwide Gross": 9000000, "US DVD Sales": null, "Production Budget": 3900000, "Release Date": "Dec 30 2025", "MPAA Rating": null, "Running Time min": null, "Distributor": "MGM", "Source": "Based on Book/Short Story", "Major Genre": "Adventure", "Creative Type": null, "Director": null, "Rotten Tomatoes Rating": null, "IMDB Rating": 8.2, "IMDB Votes": 58510},
    {"Title": "Ben-Hur", "US Gross": 73000000, "Worldwide Gross": 73000000, "US DVD Sales": null, "Production Budget": 15000000, "Release Date": "Nov 18 1959", "MPAA Rating": null, "Running Time min": null, "Distributor": "MGM", "Source": "Based on Book/Short Story", "Major Genre": "Adventure", "Creative Type": null, "Director": "William Wyler", "Rotten Tomatoes Rating": 91, "IMDB Rating": 8.2, "IMDB Votes": 58510},
    {"Title": "Benji", "US Gross": 31559560, "Worldwide Gross": 31559560, "US DVD Sales": null, "Production Budget": 500000, "Release Date": "Nov 15 1974", "MPAA Rating": null, "Running Time min": null, "Distributor": null, "Source": "Original Screenplay", "Major Genre": "Adventure", "Creative Type": null, "Director": null, "Rotten Tomatoes Rating": 83, "IMDB Rating": 5.8, "IMDB Votes": 1801},
    {"Title": "Before Sunrise", "US Gross": 5274005, "Worldwide Gross": 5274005, "US DVD Sales": null, "Production Budget": 2500000, "Release Date": "Jan 27 1995", "MPAA Rating": "R", "Running Time min": null, "Distributor": "Sony Pictures", "Source": "Original Screenplay", "Major Genre": "Drama", "Creative Type": "Contemporary Fiction", "Director": "Richard Linklater", "Rotten Tomatoes Rating": 100, "IMDB Rating": 8, "IMDB Votes": 39705},
    {"Title": "Beauty and the Beast", "US Gross": 171340294, "Worldwide Gross": 403476931, "US DVD Sales": null, "Production Budget": 20000000, "Release Date": "Nov 13 1991", "MPAA Rating": "G", "Running Time min": null, "Distributor": "Walt Disney Pictures", "Source": "Based on Book/Short Story", "Major Genre": "Musical", "Creative Type": "Fantasy", "Director": "Gary Trousdale", "Rotten Tomatoes Rating": 93, "IMDB Rating": 3.4, "IMDB Votes": 354},
    {"Title": "The Best Years of Our Lives", "US Gross": 23600000, "Worldwide Gross": 23600000, "US DVD Sales": null, "Production Budget": 2100000, "Release Date": "Nov 21 2046", "MPAA Rating": null, "Running Time min": null, "Distributor": "RKO Radio Pictures", "Source": "Based on Book/Short Story", "Major Genre": "Drama", "Creative Type": null, "Director": "William Wyler", "Rotten Tomatoes Rating": 97, "IMDB Rating": 8.2, "IMDB Votes": 17338},
    {"Title": "The Ballad of Gregorio Cortez", "US Gross": 909000, "Worldwide Gross": 909000, "US DVD Sales": null, "Production Budget": 1305000, "Release Date": "Aug 19 1983", "MPAA Rating": null, "Running Time min": null, "Distributor": "Embassy", "Source": "Based on Book/Short Story", "Major Genre": "Western", "Creative Type": "Historical Fiction", "Director": null, "Rotten Tomatoes Rating": null, "IMDB Rating": null, "IMDB Votes": null},
    {"Title": "My Big Fat Independent Movie", "US Gross": 4655, "Worldwide Gross": 4655, "US DVD Sales": null, "Production Budget": 3000000, "Release Date": "Sep 30 2005", "MPAA Rating": "R", "Running Time min": null, "Distributor": "Big Fat Movies", "Source": null, "Major Genre": "Comedy", "Creative Type": "Contemporary Fiction", "Director": null, "Rotten Tomatoes Rating": 23, "IMDB Rating": 3.2, "IMDB Votes": 1119},
    {"Title": "Battle for the Planet of the Apes", "US Gross": 8800000, "Worldwide Gross": 8800000, "US DVD Sales": null, "Production Budget": 1800000, "Release Date": "Dec 31 1972", "MPAA Rating": null, "Running Time min": null, "Distributor": "20th Century Fox", "Source": null, "Major Genre": null, "Creative Type": "Science Fiction", "Director": "Jack Lee Thompson", "Rotten Tomatoes Rating": 38, "IMDB Rating": 5, "IMDB Votes": 6094},
    {"Title": "Big Things", "US Gross": 0, "Worldwide Gross": 0, "US DVD Sales": null, "Production Budget": 50000, "Release Date": "Dec 31 2009", "MPAA Rating": null, "Running Time min": null, "Distributor": null, "Source": null, "Major Genre": null, "Creative Type": null, "Director": null, "Rotten Tomatoes Rating": null, "IMDB Rating": null, "IMDB Votes": null},
    {"Title": "Bogus", "US Gross": 4357406, "Worldwide Gross": 4357406, "US DVD Sales": null, "Production Budget": 32000000, "Release Date": "Sep 06 1996", "MPAA Rating": "PG", "Running Time min": null, "Distributor": "Warner Bros.", "Source": "Original Screenplay", "Major Genre": "Comedy", "Creative Type": "Fantasy", "Director": "Norman Jewison", "Rotten Tomatoes Rating": 40, "IMDB Rating": 4.8, "IMDB Votes": 2742},
    {"Title": "Beverly Hills Cop", "US Gross": 234760478, "Worldwide Gross": 316300000, "US DVD Sales": null, "Production Budget": 15000000, "Release Date": "Dec 05 1984", "MPAA Rating": null, "Running Time min": null, "Distributor": "Paramount Pictures", "Source": "Original Screenplay", "Major Genre": "Action", "Creative Type": "Contemporary Fiction", "Director": "Martin Brest", "Rotten Tomatoes Rating": 83, "IMDB Rating": 7.3, "IMDB Votes": 45065},
    {"Title": "Beverly Hills Cop II", "US Gross": 153665036, "Worldwide Gross": 276665036, "US DVD Sales": null, "Production Budget": 20000000, "Release Date": "May 20 1987", "MPAA Rating": "R", "Running Time min": null, "Distributor": "Paramount Pictures", "Source": "Original Screenplay", "Major Genre": "Action", "Creative Type": "Contemporary Fiction", "Director": "Tony Scott", "Rotten Tomatoes Rating": 46, "IMDB Rating": 6.1, "IMDB Votes": 29712},
    {"Title": "Beverly Hills Cop III", "US Gross": 42586861, "Worldwide Gross": 119180938, "US DVD Sales": null, "Production Budget": 50000000, "Release Date": "May 25 1994", "MPAA Rating": "R", "Running Time min": null, "Distributor": "Paramount Pictures", "Source": "Original Screenplay", "Major Genre": "Action", "Creative Type": "Contemporary Fiction", "Director": "John Landis", "Rotten Tomatoes Rating": 10, "IMDB Rating": 5, "IMDB Votes": 21199},
    {"Title": "The Black Hole", "US Gross": 35841901, "Worldwide Gross": 35841901, "US DVD Sales": null, "Production Budget": 20000000, "Release Date": "Dec 21 1979", "MPAA Rating": null, "Running Time min": null, "Distributor": "Walt Disney Pictures", "Source": "Original Screenplay", "Major Genre": null, "Creative Type": "Science Fiction", "Director": null, "Rotten Tomatoes Rating": 42, "IMDB Rating": 5.6, "IMDB Votes": 7810},
    {"Title": "Bathory", "US Gross": 0, "Worldwide Gross": 3436763, "US DVD Sales": null, "Production Budget": 15000000, "Release Date": "Jul 10 2008", "MPAA Rating": null, "Running Time min": null, "Distributor": null, "Source": null, "Major Genre": null, "Creative Type": null, "Director": null, "Rotten Tomatoes Rating": null, "IMDB Rating": 6.1, "IMDB Votes": 1446},
    {"Title": "Big", "US Gross": 114968774, "Worldwide Gross": 151668774, "US DVD Sales": null, "Production Budget": 18000000, "Release Date": "Jun 03 1988", "MPAA Rating": null, "Running Time min": null, "Distributor": "20th Century Fox", "Source": "Original Screenplay", "Major Genre": "Comedy", "Creative Type": "Fantasy", "Director": "Penny Marshall", "Rotten Tomatoes Rating": 96, "IMDB Rating": 7.2, "IMDB Votes": 49256},
    {"Title": "The Big Parade", "US Gross": 11000000, "Worldwide Gross": 22000000, "US DVD Sales": null, "Production Budget": 245000, "Release Date": "Jan 01 2025", "MPAA Rating": null, "Running Time min": null, "Distributor": "MGM", "Source": "Based on Play", "Major Genre": "Drama", "Creative Type": null, "Director": "King Vidor", "Rotten Tomatoes Rating": 100, "IMDB Rating": 8.4, "IMDB Votes": 2600},
    {"Title": "Boyz n the Hood", "US Gross": 56190094, "Worldwide Gross": 56190094, "US DVD Sales": null, "Production Budget": 6500000, "Release Date": "Jul 12 1991", "MPAA Rating": null, "Running Time min": null, "Distributor": "Sony Pictures", "Source": "Original Screenplay", "Major Genre": "Drama", "Creative Type": "Contemporary Fiction", "Director": "John Singleton", "Rotten Tomatoes Rating": 98, "IMDB Rating": 7.8, "IMDB Votes": 30299},
    {"Title": "The Book of Mormon Movie, Volume 1: The Journey", "US Gross": 1660865, "Worldwide Gross": 1660865, "US DVD Sales": null, "Production Budget": 2000000, "Release Date": "Sep 12 2003", "MPAA Rating": "PG", "Running Time min": null, "Distributor": "Distributor Unknown", "Source": "Based on Book/Short Story", "Major Genre": "Drama", "Creative Type": "Historical Fiction", "Director": null, "Rotten Tomatoes Rating": null, "IMDB Rating": null, "IMDB Votes": null},
    {"Title": "Return to the Blue Lagoon", "US Gross": 2000000, "Worldwide Gross": 2000000, "US DVD Sales": null, "Production Budget": 11000000, "Release Date": "Dec 31 1990", "MPAA Rating": null, "Running Time min": null, "Distributor": null, "Source": null, "Major Genre": null, "Creative Type": null, "Director": null, "Rotten Tomatoes Rating": null, "IMDB Rating": 4.3, "IMDB Votes": 4632},
    {"Title": "Bright Lights, Big City", "US Gross": 16118077, "Worldwide Gross": 16118077, "US DVD Sales": null, "Production Budget": 25000000, "Release Date": "Apr 01 1988", "MPAA Rating": "R", "Running Time min": null, "Distributor": "United Artists", "Source": "Based on Book/Short Story", "Major Genre": "Drama", "Creative Type": "Contemporary Fiction", "Director": null, "Rotten Tomatoes Rating": 61, "IMDB Rating": 6.8, "IMDB Votes": 11929},
    {"Title": "The Blue Bird", "US Gross": 887000, "Worldwide Gross": 887000, "US DVD Sales": null, "Production Budget": 1200000, "Release Date": "Dec 31 1975", "MPAA Rating": null, "Running Time min": null, "Distributor": "20th Century Fox", "Source": "Based on Play", "Major Genre": null, "Creative Type": "Fantasy", "Director": "George Cukor", "Rotten Tomatoes Rating": null, "IMDB Rating": 4.9, "IMDB Votes": 359},
    {"Title": "The Blue Butterfly", "US Gross": 1610194, "Worldwide Gross": 1610194, "US DVD Sales": null, "Production Budget": 10400000, "Release Date": "Feb 20 2004", "MPAA Rating": "PG", "Running Time min": null, "Distributor": "Alliance", "Source": "Original Screenplay", "Major Genre": "Drama", "Creative Type": "Contemporary Fiction", "Director": null, "Rotten Tomatoes Rating": 44, "IMDB Rating": 6.2, "IMDB Votes": 817},
    {"Title": "Blade Runner", "US Gross": 32656328, "Worldwide Gross": 33139618, "US DVD Sales": null, "Production Budget": 28000000, "Release Date": "Jun 25 1982", "MPAA Rating": "R", "Running Time min": null, "Distributor": "Warner Bros.", "Source": "Based on Book/Short Story", "Major Genre": "Thriller/Suspense", "Creative Type": "Science Fiction", "Director": "Ridley Scott", "Rotten Tomatoes Rating": 92, "IMDB Rating": 8.3, "IMDB Votes": 185546},
    {"Title": "Bloodsport", "US Gross": 11806119, "Worldwide Gross": 11806119, "US DVD Sales": null, "Production Budget": 1500000, "Release Date": "Feb 26 1988", "MPAA Rating": null, "Running Time min": null, "Distributor": "Cannon", "Source": "Original Screenplay", "Major Genre": "Action", "Creative Type": "Contemporary Fiction", "Director": null, "Rotten Tomatoes Rating": null, "IMDB Rating": 6.2, "IMDB Votes": 19816},
    {"Title": "The Blues Brothers", "US Gross": 57229890, "Worldwide Gross": 57229890, "US DVD Sales": null, "Production Budget": 27000000, "Release Date": "Jun 20 1980", "MPAA Rating": null, "Running Time min": null, "Distributor": "Universal", "Source": "Original Screenplay", "Major Genre": "Musical", "Creative Type": "Contemporary Fiction", "Director": "John Landis", "Rotten Tomatoes Rating": 84, "IMDB Rating": 7.9, "IMDB Votes": 62941},
    {"Title": "Blow Out", "US Gross": 13747234, "Worldwide Gross": 13747234, "US DVD Sales": null, "Production Budget": 18000000, "Release Date": "Jul 24 1981", "MPAA Rating": null, "Running Time min": null, "Distributor": "Filmways Pictures", "Source": "Original Screenplay", "Major Genre": "Thriller/Suspense", "Creative Type": "Contemporary Fiction", "Director": "Brian De Palma", "Rotten Tomatoes Rating": 89, "IMDB Rating": 7.1, "IMDB Votes": 10239},
    {"Title": "De battre mon coeur s'est arrÍtÈ", "US Gross": 1023424, "Worldwide Gross": 8589831, "US DVD Sales": null, "Production Budget": 5500000, "Release Date": "Jul 01 2005", "MPAA Rating": "Not Rated", "Running Time min": null, "Distributor": "WellSpring", "Source": "Original Screenplay", "Major Genre": "Drama", "Creative Type": "Contemporary Fiction", "Director": null, "Rotten Tomatoes Rating": null, "IMDB Rating": 7.3, "IMDB Votes": 7295},
    {"Title": "The Broadway Melody", "US Gross": 2800000, "Worldwide Gross": 4358000, "US DVD Sales": null, "Production Budget": 379000, "Release Date": "Dec 31 1928", "MPAA Rating": null, "Running Time min": null, "Distributor": "MGM", "Source": "Original Screenplay", "Major Genre": "Musical", "Creative Type": null, "Director": null, "Rotten Tomatoes Rating": 38, "IMDB Rating": 6.7, "IMDB Votes": 2017},
    {"Title": "Boom Town", "US Gross": 9172000, "Worldwide Gross": 9172000, "US DVD Sales": null, "Production Budget": 2000000, "Release Date": "Dec 31 1939", "MPAA Rating": null, "Running Time min": null, "Distributor": "MGM", "Source": "Original Screenplay", "Major Genre": null, "Creative Type": null, "Director": null, "Rotten Tomatoes Rating": null, "IMDB Rating": 7.1, "IMDB Votes": 1115},
    {"Title": "Bound", "US Gross": 3802260, "Worldwide Gross": 6300000, "US DVD Sales": null, "Production Budget": 4500000, "Release Date": "Oct 04 1996", "MPAA Rating": "R", "Running Time min": null, "Distributor": "Gramercy", "Source": "Original Screenplay", "Major Genre": "Thriller/Suspense", "Creative Type": "Contemporary Fiction", "Director": "Andy Wachowski", "Rotten Tomatoes Rating": 88, "IMDB Rating": 7.4, "IMDB Votes": 23564},
    {"Title": "Bang", "US Gross": 527, "Worldwide Gross": 527, "US DVD Sales": null, "Production Budget": 10000, "Release Date": "Apr 01 1996", "MPAA Rating": null, "Running Time min": null, "Distributor": "JeTi Films", "Source": "Original Screenplay", "Major Genre": "Thriller/Suspense", "Creative Type": "Contemporary Fiction", "Director": "Jeff \"\"King Jeff\"\" Hollins", "Rotten Tomatoes Rating": null, "IMDB Rating": 6.3, "IMDB Votes": 369},
    {"Title": "Bananas", "US Gross": null, "Worldwide Gross": null, "US DVD Sales": null, "Production Budget": 2000000, "Release Date": "Apr 28 1971", "MPAA Rating": "PG-13", "Running Time min": null, "Distributor": "MGM", "Source": "Original Screenplay", "Major Genre": "Comedy", "Creative Type": null, "Director": "Woody Allen", "Rotten Tomatoes Rating": 89, "IMDB Rating": 7.1, "IMDB Votes": 12415},
    {"Title": "Bill & Ted's Bogus Journey", "US Gross": 37537675, "Worldwide Gross": 37537675, "US DVD Sales": null, "Production Budget": 20000000, "Release Date": "Jul 19 1991", "MPAA Rating": null, "Running Time min": null, "Distributor": "Orion Pictures", "Source": "Original Screenplay", "Major Genre": "Comedy", "Creative Type": "Fantasy", "Director": "Peter Hewitt", "Rotten Tomatoes Rating": 58, "IMDB Rating": 5.8, "IMDB Votes": 20188},
    {"Title": "The Birth of a Nation", "US Gross": 10000000, "Worldwide Gross": 11000000, "US DVD Sales": null, "Production Budget": 110000, "Release Date": "Feb 08 2015", "MPAA Rating": null, "Running Time min": null, "Distributor": null, "Source": "Based on Book/Short Story", "Major Genre": "Drama", "Creative Type": null, "Director": null, "Rotten Tomatoes Rating": 100, "IMDB Rating": 7.1, "IMDB Votes": 8901},
    {"Title": "The Ballad of Cable Hogue", "US Gross": 3500000, "Worldwide Gross": 5000000, "US DVD Sales": null, "Production Budget": 3716946, "Release Date": "May 13 1970", "MPAA Rating": null, "Running Time min": null, "Distributor": "Warner Bros.", "Source": "Original Screenplay", "Major Genre": "Western", "Creative Type": "Historical Fiction", "Director": "Sam Peckinpah", "Rotten Tomatoes Rating": 92, "IMDB Rating": 7.3, "IMDB Votes": 3125},
    {"Title": "The Blood of Heroes", "US Gross": 882290, "Worldwide Gross": 882290, "US DVD Sales": null, "Production Budget": 7700000, "Release Date": "Feb 23 1990", "MPAA Rating": null, "Running Time min": null, "Distributor": "New Line", "Source": "Original Screenplay", "Major Genre": "Action", "Creative Type": null, "Director": null, "Rotten Tomatoes Rating": null, "IMDB Rating": 6.2, "IMDB Votes": 2523},
    {"Title": "The Blood of My Brother: A Story of Death in Iraq", "US Gross": 0, "Worldwide Gross": 0, "US DVD Sales": null, "Production Budget": 120000, "Release Date": "Jun 30 2006", "MPAA Rating": null, "Running Time min": null, "Distributor": "Lifesize Entertainment", "Source": "Based on Real Life Events", "Major Genre": "Documentary", "Creative Type": "Factual", "Director": null, "Rotten Tomatoes Rating": 71, "IMDB Rating": 7.6, "IMDB Votes": 90},
    {"Title": "Boomerang", "US Gross": 70052444, "Worldwide Gross": 131052444, "US DVD Sales": null, "Production Budget": 42000000, "Release Date": "Jul 01 1992", "MPAA Rating": null, "Running Time min": null, "Distributor": "Paramount Pictures", "Source": "Original Screenplay", "Major Genre": "Comedy", "Creative Type": "Contemporary Fiction", "Director": null, "Rotten Tomatoes Rating": 37, "IMDB Rating": 5.9, "IMDB Votes": 202},
    {"Title": "The Bridge on the River Kwai", "US Gross": 33300000, "Worldwide Gross": 33300000, "US DVD Sales": null, "Production Budget": 3000000, "Release Date": "Dec 18 1957", "MPAA Rating": null, "Running Time min": null, "Distributor": "Sony/Columbia", "Source": "Based on Book/Short Story", "Major Genre": "Drama", "Creative Type": null, "Director": "David Lean", "Rotten Tomatoes Rating": 95, "IMDB Rating": 8.4, "IMDB Votes": 58641}
      ],
      books : [
  {
    "author": "Chinua Achebe",
    "country": "Nigeria",
    "imageLink": "images/things-fall-apart.jpg",
    "language": "English",
    "link": "https://en.wikipedia.org/wiki/Things_Fall_Apart\n",
    "pages": 209,
    "title": "Things Fall Apart",
    "year": 1958
  },
  {
    "author": "Hans Christian Andersen",
    "country": "Denmark",
    "imageLink": "images/fairy-tales.jpg",
    "language": "Danish",
    "link": "https://en.wikipedia.org/wiki/Fairy_Tales_Told_for_Children._First_Collection.\n",
    "pages": 784,
    "title": "Fairy tales",
    "year": 1836
  },
  {
    "author": "Dante Alighieri",
    "country": "Italy",
    "imageLink": "images/the-divine-comedy.jpg",
    "language": "Italian",
    "link": "https://en.wikipedia.org/wiki/Divine_Comedy\n",
    "pages": 928,
    "title": "The Divine Comedy",
    "year": 1315
  },
  {
    "author": "Unknown",
    "country": "Sumer and Akkadian Empire",
    "imageLink": "images/the-epic-of-gilgamesh.jpg",
    "language": "Akkadian",
    "link": "https://en.wikipedia.org/wiki/Epic_of_Gilgamesh\n",
    "pages": 160,
    "title": "The Epic Of Gilgamesh",
    "year": -1700
  },
  {
    "author": "Unknown",
    "country": "Achaemenid Empire",
    "imageLink": "images/the-book-of-job.jpg",
    "language": "Hebrew",
    "link": "https://en.wikipedia.org/wiki/Book_of_Job\n",
    "pages": 176,
    "title": "The Book Of Job",
    "year": -600
  },
  {
    "author": "Unknown",
    "country": "India/Iran/Iraq/Egypt/Tajikistan",
    "imageLink": "images/one-thousand-and-one-nights.jpg",
    "language": "Arabic",
    "link": "https://en.wikipedia.org/wiki/One_Thousand_and_One_Nights\n",
    "pages": 288,
    "title": "One Thousand and One Nights",
    "year": 1200
  },
  {
    "author": "Unknown",
    "country": "Iceland",
    "imageLink": "images/njals-saga.jpg",
    "language": "Old Norse",
    "link": "https://en.wikipedia.org/wiki/Nj%C3%A1ls_saga\n",
    "pages": 384,
    "title": "Nj\u00e1l's Saga",
    "year": 1350
  },
  {
    "author": "Jane Austen",
    "country": "United Kingdom",
    "imageLink": "images/pride-and-prejudice.jpg",
    "language": "English",
    "link": "https://en.wikipedia.org/wiki/Pride_and_Prejudice\n",
    "pages": 226,
    "title": "Pride and Prejudice",
    "year": 1813
  },
  {
    "author": "Honor\u00e9 de Balzac",
    "country": "France",
    "imageLink": "images/le-pere-goriot.jpg",
    "language": "French",
    "link": "https://en.wikipedia.org/wiki/Le_P%C3%A8re_Goriot\n",
    "pages": 443,
    "title": "Le P\u00e8re Goriot",
    "year": 1835
  },
  {
    "author": "Samuel Beckett",
    "country": "Republic of Ireland",
    "imageLink": "images/molloy-malone-dies-the-unnamable.jpg",
    "language": "French, English",
    "link": "https://en.wikipedia.org/wiki/Molloy_(novel)\n",
    "pages": 256,
    "title": "Molloy, Malone Dies, The Unnamable, the trilogy",
    "year": 1952
  },
  {
    "author": "Giovanni Boccaccio",
    "country": "Italy",
    "imageLink": "images/the-decameron.jpg",
    "language": "Italian",
    "link": "https://en.wikipedia.org/wiki/The_Decameron\n",
    "pages": 1024,
    "title": "The Decameron",
    "year": 1351
  },
  {
    "author": "Jorge Luis Borges",
    "country": "Argentina",
    "imageLink": "images/ficciones.jpg",
    "language": "Spanish",
    "link": "https://en.wikipedia.org/wiki/Ficciones\n",
    "pages": 224,
    "title": "Ficciones",
    "year": 1965
  },
  {
    "author": "Emily Bront\u00eb",
    "country": "United Kingdom",
    "imageLink": "images/wuthering-heights.jpg",
    "language": "English",
    "link": "https://en.wikipedia.org/wiki/Wuthering_Heights\n",
    "pages": 342,
    "title": "Wuthering Heights",
    "year": 1847
  },
  {
    "author": "Albert Camus",
    "country": "Algeria, French Empire",
    "imageLink": "images/l-etranger.jpg",
    "language": "French",
    "link": "https://en.wikipedia.org/wiki/The_Stranger_(novel)\n",
    "pages": 185,
    "title": "The Stranger",
    "year": 1942
  },
  {
    "author": "Paul Celan",
    "country": "Romania, France",
    "imageLink": "images/poems-paul-celan.jpg",
    "language": "German",
    "link": "\n",
    "pages": 320,
    "title": "Poems",
    "year": 1952
  },
  {
    "author": "Louis-Ferdinand C\u00e9line",
    "country": "France",
    "imageLink": "images/voyage-au-bout-de-la-nuit.jpg",
    "language": "French",
    "link": "https://en.wikipedia.org/wiki/Journey_to_the_End_of_the_Night\n",
    "pages": 505,
    "title": "Journey to the End of the Night",
    "year": 1932
  },
  {
    "author": "Miguel de Cervantes",
    "country": "Spain",
    "imageLink": "images/don-quijote-de-la-mancha.jpg",
    "language": "Spanish",
    "link": "https://en.wikipedia.org/wiki/Don_Quixote\n",
    "pages": 1056,
    "title": "Don Quijote De La Mancha",
    "year": 1610
  },
  {
    "author": "Geoffrey Chaucer",
    "country": "England",
    "imageLink": "images/the-canterbury-tales.jpg",
    "language": "English",
    "link": "https://en.wikipedia.org/wiki/The_Canterbury_Tales\n",
    "pages": 544,
    "title": "The Canterbury Tales",
    "year": 1450
  },
  {
    "author": "Anton Chekhov",
    "country": "Russia",
    "imageLink": "images/stories-of-anton-chekhov.jpg",
    "language": "Russian",
    "link": "https://en.wikipedia.org/wiki/List_of_short_stories_by_Anton_Chekhov\n",
    "pages": 194,
    "title": "Stories",
    "year": 1886
  },
  {
    "author": "Joseph Conrad",
    "country": "United Kingdom",
    "imageLink": "images/nostromo.jpg",
    "language": "English",
    "link": "https://en.wikipedia.org/wiki/Nostromo\n",
    "pages": 320,
    "title": "Nostromo",
    "year": 1904
  },
  {
    "author": "Charles Dickens",
    "country": "United Kingdom",
    "imageLink": "images/great-expectations.jpg",
    "language": "English",
    "link": "https://en.wikipedia.org/wiki/Great_Expectations\n",
    "pages": 194,
    "title": "Great Expectations",
    "year": 1861
  },
  {
    "author": "Denis Diderot",
    "country": "France",
    "imageLink": "images/jacques-the-fatalist.jpg",
    "language": "French",
    "link": "https://en.wikipedia.org/wiki/Jacques_the_Fatalist\n",
    "pages": 596,
    "title": "Jacques the Fatalist",
    "year": 1796
  },
  {
    "author": "Alfred D\u00f6blin",
    "country": "Germany",
    "imageLink": "images/berlin-alexanderplatz.jpg",
    "language": "German",
    "link": "https://en.wikipedia.org/wiki/Berlin_Alexanderplatz\n",
    "pages": 600,
    "title": "Berlin Alexanderplatz",
    "year": 1929
  },
  {
    "author": "Fyodor Dostoevsky",
    "country": "Russia",
    "imageLink": "images/crime-and-punishment.jpg",
    "language": "Russian",
    "link": "https://en.wikipedia.org/wiki/Crime_and_Punishment\n",
    "pages": 551,
    "title": "Crime and Punishment",
    "year": 1866
  },
  {
    "author": "Fyodor Dostoevsky",
    "country": "Russia",
    "imageLink": "images/the-idiot.jpg",
    "language": "Russian",
    "link": "https://en.wikipedia.org/wiki/The_Idiot\n",
    "pages": 656,
    "title": "The Idiot",
    "year": 1869
  },
  {
    "author": "Fyodor Dostoevsky",
    "country": "Russia",
    "imageLink": "images/the-possessed.jpg",
    "language": "Russian",
    "link": "https://en.wikipedia.org/wiki/Demons_(Dostoyevsky_novel)\n",
    "pages": 768,
    "title": "The Possessed",
    "year": 1872
  },
  {
    "author": "Fyodor Dostoevsky",
    "country": "Russia",
    "imageLink": "images/the-brothers-karamazov.jpg",
    "language": "Russian",
    "link": "https://en.wikipedia.org/wiki/The_Brothers_Karamazov\n",
    "pages": 824,
    "title": "The Brothers Karamazov",
    "year": 1880
  },
  {
    "author": "George Eliot",
    "country": "United Kingdom",
    "imageLink": "images/middlemarch.jpg",
    "language": "English",
    "link": "https://en.wikipedia.org/wiki/Middlemarch\n",
    "pages": 800,
    "title": "Middlemarch",
    "year": 1871
  },
  {
    "author": "Ralph Ellison",
    "country": "United States",
    "imageLink": "images/invisible-man.jpg",
    "language": "English",
    "link": "https://en.wikipedia.org/wiki/Invisible_Man\n",
    "pages": 581,
    "title": "Invisible Man",
    "year": 1952
  },
  {
    "author": "Euripides",
    "country": "Greece",
    "imageLink": "images/medea.jpg",
    "language": "Greek",
    "link": "https://en.wikipedia.org/wiki/Medea_(play)\n",
    "pages": 104,
    "title": "Medea",
    "year": -431
  },
  {
    "author": "William Faulkner",
    "country": "United States",
    "imageLink": "images/absalom-absalom.jpg",
    "language": "English",
    "link": "https://en.wikipedia.org/wiki/Absalom,_Absalom!\n",
    "pages": 313,
    "title": "Absalom, Absalom!",
    "year": 1936
  }
  ],
      color: "",
      button: "",
      data: {},
      isSubmit: false,
    };
  },
  methods: {
    showMessage() {
      this.isSubmit = true;
      this.data = {color:this.color,button:this.button}
    },
  },
};
</script>